sudo: required
dist: trusty

language: python

python:
    - "2.7"

virtualenv:
    system_site_packages: true

services:
    - postgres
    - memcached
    - rabbitmq

before_install:
    - mkdir -p $HOME/bin
    - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
    - testspace config url reddit.testspace.com

install:
    - sudo apt-add-repository -y ppa:reddit/ppa -y

    - sudo apt-get update -q
    - >
        sudo apt-get install -y \
            make \
            pylint \
            python-beautifulsoup \
            python-bcrypt \
            python-coverage \
            python-mock \
            python-nose \
            python-pip \
            python-pylons \
            python-tz \
            python-snudown 

    - sudo pip install flake8>=3.5.0
    - sudo pip install baseplate
    - sudo pip install flake8_formatter_junit_xml
#    - sudo install/travis.sh travis .

before_script:
    - install/setup_rabbitmq.sh
    - install/setup_postgres.sh
#    - install/setup_cassandra.sh

script:
    - cd r2
    - nosetests
    - flake8 r2/tests
